- name: Install extra packages
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - browser-plugin-vlc
    - calibre
    - gimp
    - inkscape
    - transmission
    - ubuntu-restricted-addons
    - ubuntu-restricted-extras
    - virtualbox
    - python-gpgme

